services:
  deckster-ui:
    container_name: deckster-ui
    image: ghcr.io/bogdan23a/deckster-ui:master
    env_file:
      - ./.ui.env
    ports:
      - "5173:5173"

  deckster:
    container_name: deckster
    image: ghcr.io/bogdan23a/deckster:master
    restart: unless-stopped
    ports:
      - "9090:9090"
    env_file:
      - ./.env
    depends_on:
      cockroach:
        condition: service_healthy

  cockroach:
    container_name: cockroach
    image: cockroachdb/cockroach:latest
    ports:
      - '26257:26257'
      - '8080:8080'
    restart: unless-stopped
    command: start-single-node --insecure
    healthcheck:
      test: curl http://localhost:8080/health
      start_period: 60s
      timeout: 5s
      interval: 1s
      retries: 50

  cockroach-init:
    container_name: cockroach-init
    image: cockroachdb/cockroach:latest
    depends_on:
      cockroach:
        condition: service_healthy
    volumes:
      - ./cockroach-data/:/home/
    entrypoint: /bin/bash
    command: /home/setup.sh