spring:
  application:
    name: deckster
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  flyway:
    locations: classpath:/db/migration
    schemas: game, player, deck, card, card_type, game_card
    baseline-on-migrate: true
    enabled: true
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT}