spring:
  application:
    name: deckster
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  #  router:
#    static-resources:
#      swagger:
#        paths: classpath:META-INF/swagger
#        mapping: /swagger/**
#      swagger-ui:
#        paths: classpath:META-INF/swagger/views/swagger-ui
#        mapping: /swagger-ui/**
#netty:
#  default:
#    allocator:
#      max-order: 3

  flyway:
    locations: classpath:/db/migration
    schemas: game, player, deck, card, card_type
    baseline-on-migrate: true
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:26257/deckster
    driver-class-name: org.postgresql.Driver
    username: deckster
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9090