services:
  deckster-ui:
    container_name: ui
    image: deckster-ui
    ports:
      - 3000:3000
  deckster:
    container_name: deckster
    image: deckster
    restart: unless-stopped
    ports:
      - 9090:9090
    env_file:
      - .env
    depends_on:
      cockroach:
        condition: service_started
      cockroach-init:
        condition: service_completed_successfully
  cockroach:
    container_name: 'cockroach'
    image: cockroachdb/cockroach:latest
    ports:
      - '26257:26257'
      - '8080:8080'
    restart: unless-stopped
    command: start-single-node --insecure
    healthcheck:
      test: wget -0 - -q http://localhost:26257
      start_period: 60s
      timeout: 5s
      interval: 10s
      retries: 50

  cockroach-init:
    container_name: 'cockroach-init'
    image: cockroachdb/cockroach:latest
    depends_on:
      'cockroach':
        condition: service_started
    volumes:
      - ./cockroach-data/:/home/
    entrypoint: /bin/bash
    command: /home/setup.sh

networks:
  net:
    driver: bridge
  internet:
  proxy:
    internal: true